apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://192.168.99.100:8443
    k8sVersion: v1.10.0
    path: default
  minikube:
    destination:
      namespace: default
      server: https://192.168.99.100:8443
    k8sVersion: v1.7.0
    path: minikube
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 692596e912395e7a92f134a80c2b87b2898109f1
      refSpec: master
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 692596e912395e7a92f134a80c2b87b2898109f1
      refSpec: master
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 692596e912395e7a92f134a80c2b87b2898109f1
      refSpec: master
    name: tf-serving
    registry: kubeflow
name: my-kubeflow
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 692596e912395e7a92f134a80c2b87b2898109f1
      refSpec: master
    protocol: github
    uri: github.com/google/kubeflow/tree/master/kubeflow
version: 0.0.1
